### ISSUE TITLE
仮のページを作る

### ISSUE THREAD

**Issue by ywenli** [ywenli/circle#1]
# これは？

仮のトップページを作ります。

## todo

- [x] ルーティング追加
- [x] home contoller
- [x] viewの編集
	- [x] full_title helper 追加
- [x] gem: rspec導入
- [x] test for page conrolelr追加
- [x] test for applciation helper追加
- [x] gem: bootstrap導入
	cf. https://github.com/twbs/bootstrap-rubygem
- [x] gem: webdriver導入
	chromedriver-helper, selenium-webdriverは削除

## 備考

なし
